# === Streamlit ===
streamlit:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: streamlit_app
  restart: always
  environment:
    - STREAMLIT_SERVER_HEADLESS=true
    - STREAMLIT_SERVER_PORT=8501
    - PYTHONUNBUFFERED=1
    - VIRTUAL_HOST=miamigo-bot.duckdns.org
    - LETSENCRYPT_HOST=miamigo-bot.duckdns.org
    - LETSENCRYPT_EMAIL=brouckeh@gmail.com
  expose:
    - "8501"
  depends_on:
    - postgres
    - minio
  networks:
    - miamigo_net

# === N8N ===
n8n:
  image: n8nio/n8n:1.114.4
  container_name: n8n_main
  restart: always
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=n8n
    - DB_POSTGRESDB_USER=n8n
    - DB_POSTGRESDB_PASSWORD=n8npass
    - N8N_SECURE_COOKIE=false
    - QUEUE_MODE=true
    - QUEUE_REDIS_HOST=redis
    - EXECUTIONS_PROCESS=main
    - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=all
    - N8N_FILES_HOST=http://minio:9000
    - N8N_FILES_BUCKET_NAME=n8n
    - N8N_FILES_ACCESS_KEY_ID=minio
    - N8N_FILES_SECRET_ACCESS_KEY=minio123
    - N8N_HOST=n8n.miamigo-bot.duckdns.org
    - N8N_PORT=5678
    - N8N_PROTOCOL=https
    - WEBHOOK_TUNNEL_URL=https://n8n.miamigo-bot.duckdns.org
    - GENERIC_TIMEZONE=Europe/Paris
    - VIRTUAL_HOST=n8n.miamigo-bot.duckdns.org
    - LETSENCRYPT_HOST=n8n.miamigo-bot.duckdns.org
    - LETSENCRYPT_EMAIL=brouckeh@gmail.com
  expose:
    - "5678"
  depends_on:
    - redis
    - postgres
    - minio
  volumes:
    - n8ndata:/home/node/.n8n
  networks:
    - miamigo_net

# === MinIO ===
minio:
  image: minio/minio:latest
  command: server /data --console-address ":9001"
  restart: always
  environment:
    - MINIO_ROOT_USER=minio
    - MINIO_ROOT_PASSWORD=minio123
    - TZ=Europe/Paris
    - VIRTUAL_HOST=minio.miamigo-bot.duckdns.org
    - LETSENCRYPT_HOST=minio.miamigo-bot.duckdns.org
    - LETSENCRYPT_EMAIL=brouckeh@gmail.com
  expose:
    - "9000"
    - "9001"
  volumes:
    - miniodata:/data
  networks:
    - miamigo_net
