version: "3.8"

services:
  # === Nginx Proxy (reverse proxy dynamique) ===
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TRUST_DOWNSTREAM_PROXY=true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - miamigo_net

  # === Let's Encrypt Companion (SSL auto) ===
  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    environment:
      - DEFAULT_EMAIL=brouckeh@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - miamigo_net

  # === Streamlit App ===
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    restart: always
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - PYTHONUNBUFFERED=1
      - VIRTUAL_HOST=miamigo-bot.duckdns.org
      - LETSENCRYPT_HOST=miamigo-bot.duckdns.org
      - LETSENCRYPT_EMAIL=brouckeh@gmail.com
    expose:
      - "8501"
    depends_on:
      - postgres
      - minio
    networks:
      - miamigo_net

  # === N8N Main ===
  n8n:
    image: n8nio/n8n:1.114.4
    container_name: n8n_main
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - N8N_SECURE_COOKIE=true
      - QUEUE_MODE=true
      - QUEUE_REDIS_HOST=redis
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=all
      - N8N_FILES_HOST=http://minio:9000
      - N8N_FILES_BUCKET_NAME=n8n
      - N8N_FILES_ACCESS_KEY_ID=minio
      - N8N_FILES_SECRET_ACCESS_KEY=minio123
      - N8N_HOST=n8n.miamigo-bot.duckdns.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.miamigo-bot.duckdns.org/
      - WEBHOOK_TUNNEL_URL=https://n8n.miamigo-bot.duckdns.org
      - GENERIC_TIMEZONE=Europe/Paris
      - VIRTUAL_HOST=n8n.miamigo-bot.duckdns.org
      - LETSENCRYPT_HOST=n8n.miamigo-bot.duckdns.org
      - LETSENCRYPT_EMAIL=brouckeh@gmail.com
    expose:
      - "5678"
    depends_on:
      - redis
      - postgres
      - minio
    volumes:
      - n8ndata:/home/node/.n8n
    networks:
      - miamigo_net

  # === N8N Worker ===
  n8n-worker:
    image: n8nio/n8n:1.114.4
    container_name: n8n_worker
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - QUEUE_MODE=true
      - QUEUE_REDIS_HOST=redis
      - EXECUTIONS_PROCESS=main
      - N8N_FILES_HOST=http://minio:9000
      - N8N_FILES_BUCKET_NAME=n8n
      - N8N_FILES_ACCESS_KEY_ID=minio
      - N8N_FILES_SECRET_ACCESS_KEY=minio123
      - GENERIC_TIMEZONE=Europe/Paris
    depends_on:
      - redis
      - postgres
      - minio
    volumes:
      - n8ndata:/home/node/.n8n
    networks:
      - miamigo_net

  # === Redis ===
  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - miamigo_net

  # === PostgreSQL ===
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8npass
      - POSTGRES_DB=n8n
      - TZ=Europe/Paris
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - miamigo_net

  # === MinIO ===
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - TZ=Europe/Paris
      - VIRTUAL_HOST=minio.miamigo-bot.duckdns.org
      - LETSENCRYPT_HOST=minio.miamigo-bot.duckdns.org
      - LETSENCRYPT_EMAIL=brouckeh@gmail.com
    expose:
      - "9000"
      - "9001"
    volumes:
      - miniodata:/data
    networks:
      - miamigo_net

# === Volumes persistants ===
volumes:
  n8ndata:
  pgdata:
  miniodata:

# === Réseau partagé ===
networks:
  miamigo_net:
    driver: bridge
