[auth]
redirect_uri = "https://miamigo-bot.duckdns.org:8501/oauth2callback"
cookie_secret = "ziefhyerfbhsvbsybvusevsrg49458PDFLKODFV="
[auth.google]
client_id = "18710123753-3g790m7oso8eva2sqkopu4i7rf0ia4df.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
