[auth]
redirect_uri = "https://miamigo-bot.duckdns.org:8443/oauth2callback"
cookie_secret = "ziefhyerfbhsvbsybvusevsrg49458PDFLKODFV="
[auth.google]
client_id = "18710123753-ca9kj8bb5b3hs8gh7j5i9g95nu9kn2d2.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
