[auth]
redirect_uri = "https://miamigo-bot.duckdns.org/oauth2callback"
cookie_secret = "ziefhyerfbhsvbsybvusevsrg49458PDFLKODFV="
[auth.google]
client_id = "18710123753-jrh4ue0ifmvqhfv7or150laml7rieo5u.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
